apiVersion: v1
kind: Secret
metadata:
  name: polis-server-secret
type: Opaque
data:
  # DATABASE_URL: postgres://polistestu:polistestpw@host.docker.internal:5432/polistestdb
  # base64 encoded value: 
  # DATABASE_URL: cG9zdGdyZXM6Ly9wb2xpc3Rlc3R1OnBvbGlzdGVzdHB3QGhvc3QuZG9ja2VyLmludGVybmFsOjU0MzIvcG9saXN0ZXN0ZGI=
  # ---
  # DATABASE_URL: postgres://polisdbu:polisdbpw@host.docker.internal:5432/polisdevlocaldb
  # Example: echo 'postgres://polisdbu:polisdbpw@host.docker.internal:5432/polisdevlocaldb' | base64 -w 0
  # base64 encoded value: 
  DATABASE_URL: cG9zdGdyZXM6Ly9wb2xpc2RidTpwb2xpc2RicHdAaG9zdC5kb2NrZXIuaW50ZXJuYWw6NTQzMi9wb2xpc2RldmxvY2FsZGIK  
  # base64 encoded value:  
  MAILGUN_API_KEY: CHANGEME
  # base64 encoded value:  
  # GOOGLE_CREDENTIALS_BASE64: CHANGEME
  
  
